project:
  type: manuscript
  preview:
    port: 7601

manuscript:
  article: proposal-2026-03.qmd
  meca-bundle: false

preview-mode: raw

format:
  html:
    comments:
      hypothesis: true
  docx: default

  # (other formats)
  pdf: default



exclude:
  - "messy_notes/"

execute:
  freeze: true



