---
title: Notes
author: Frederik J. Van Deventer
bibliography: references.bib

---

- "While privacy is recognised as a right by some African states, this is only rarely translated into justiciable rights and is almost never a constraint on the behaviour of governments and their secret police. This can be seen in the areas of data protection, surveillance and cybersecurity." - @sutherlandDigitalPrivacyAfrica2018



### Hypotheses to work with or maxims and possible case studies

- Digital divide discourse is not advancing the closing of the divide
  - 
- Closing the digital divide is not alleviating poverty
- Big tech's push for the next billion users is unethically preying on the new and inexperienced users
- Improving privacy literacy will improve a users engagement with platforms 
- Privacy and security are low priority
- The global south is likely to fall prey to exposurism or pilotism, the idea that companies use interventions and experiments to test a theory and increase their PR by showing that they are involved in "community efforts"
  - Why is it likely to fall prey? Or are they able to rise above.
  - shown by humanitarianism in Technocolonialism
- AI hype and positivity nudges people to put their trust in platforms, but support will lack in the future
  - who will benefit [@houstonDigitalDivideWho2002]
- Technosolutionism puts too much trust in AI and will ask from new users to engage with these tools. These tools are not free and cost a lot to maintain
- Offline-first education tools.
- Data protection regulation is not being enforced and falls short.
- Machine learning's biases are implicit but not without consequence
  - example DRC refugees: @madianou2024technocolonialism p.140. When the decision is made by the machine without any clear explanation about the criteria used, then it is harder to challenge [.. exclusion].
  - Example Australia robodebt.



## gesprek Eelco
_ Bart Jacobs - Digital security.
_ Jaap Henk Hoepman - Fundamentalist privacy, data minimalisation. Digital security
_  - Misgaan met data
_ 

Theoretical Framework

- Privacy
-  Helen Nissenbaum Contextual Integrity (up and own the data food chain)
- Mireille Hildebrandt ()
- Timothy Garton Ash: Free Speech

Big Tech en hun algoritmen vs. perceptie privacy in Botswana en wat aanvaarden mensen.  

Association Computer and Machinery
  - Chapter India, China
  - Chapter Africa
  - Technology policy council