---
title: PhD Proposal
authors:
  - name: Frederik J van Deventer
    affiliation: HAN University of Applied Sciences
    roles: writing
    corresponding: true
bibliography: references.bib
mainfont: Palatino
# mainfont: Latin Modern Roman
sansfont: Palatino
---

## Why don't we care about privacy?

- similar to not caring about the environment
- vegetarianism
- dopanmine, addiction to social media
- necessity. gmail is just so cheap
  
### solution

Prevalence, front of mind consequence meditation

## Introduction

As humans in a digital society we are living lives that are entwined with technology that exchanges data. We need to exchange data to track our businesses, for our communications with friends and family, to come ahead in our educational system, to pay our taxes etcetera, etcetera. We sacrifice our privacy to get access to free applications or to benefit our security [@mckinnon2014sacrificing], or move along faster in a health system [], or even to register for asylum [@lodinovaApplicationBiometricsMeans2016]. These applications typically track our internet behaviour [@makhortykhTrackNotTrack2022;@razaghpanahAppsTrackersPrivacy2018]. This tracking of biometric, location and social data is not without danger, this data is also used for the creation of economic value and has lead to something more than just a phenomenon of capitalism; it's a manifestation of colonialism [@couldry2019data].

With new developments in AI this becomes more prevalent as data and AI "entrench power assymetries and engender new forms of structural violence and new inequities between the Global South and North" [@madianou2024technocolonialism]. There is little to no protection or privacy for private consumers unless government regulation explicitly makes it so, like the GDPR program [@arora2019general]. Much of Global South legislation is lagging behind or has met with challenges in enforcing the laws set in place [@prinslooDataPrivacyAfrican2022]. 

In light of this

_Directions this could take. Validating all these promises AI seems to make. And vouching for privacy or security of the data disclosed with these agents._

<!-- Third parties are becoming an integral part of government policy to deal with the process of data collection and analysis [@johnson2023owns]. -->
<!-- 
> Most countries outside the West have lax or no privacy laws (Taylor, Floridi, and van der Sloot 2016). Brazil passed its first privacy laws in 2014, while India passed some in 2017. - [@arora2019general]

__governance__ __legislation__ -->



## Research Questions

In what way can power assymetries between the majority world and the minority world be limited by effective legislation towards protecting personal data of citizens?

How can privacy literacy be increased that respects a cultural tradition without using a Eurocentric view of individual privacy but including a collective privacy?

What does privacy mean in rural areas


## Methodology

- Qualitative investigation of policy, laws in different countries
- Questionnaire on usage of internet and awareness of privacy concerns..


## References



### Conversation Payal

Components of privacy. How does it enable me to work online.

- guardianship system in middle east (26 countries)
  - tracking by patriarch
- privacy doesn't enable freedom
- afghanistan: privacy
  - data extraction
- missing complexities
  - authoritartion regimes --> willing to 
  - 
- sense context
  - qualms of literacy to feel enabled 
  - prompt literacy
  - trust literacy

- enabling to function within these context
  
- idea: microsoft grant with red cross
  - call for microsoft grant
  - upscaling humanitarian workforces with ai
  - 

- Inclusive AILAB

Title: Upskilling Humanitarian Workforces in the AI Economy: How Generative AI is Impacting Global Humanitarian Contexts
Principal Investigator: Prof. Payal Arora, Chair of Inclusive AI Cultures, Utrecht University and Cofounder of Inclusive AI Lab
Partners: International Federation of the Red Cross and Red Crescent Societies (IFRC), IFRC Solferino Academy, Netherlands Red Cross Society, LINRE-Asia
 
 
Research theme
AI and National Diffusion Differences
Summary of the Project (99/100 words)
This project examines how generative AI is reshaping humanitarian volunteering, a global workforce of 970 million often overlooked in digital transformation agendas. Centering on Red Cross volunteers in Sri Lanka, Kenya, and the Netherlands, it analyzes how adoption varies across contexts and the cultural and organizational factors that enable or hinder diffusion. Positioning volunteering as a pathway to workforce development, it explores how GenAI can enhance training, coordination, and crisis readiness while reducing inequities. Using comparative digital ethnography and action research, findings will provide policymakers, civic organizations, and global partners actionable strategies to embed inclusive AI in humanitarian ecosystems.


 ### Conversation Stijn

 - HAN-beurs
   - digi-data-vaardig genAI-literacy
- Data en IT data-awareness
  - awareness slecht --> data-gedreven werken
  - wat is data, wat zou data kunnen zijn
  - privacy, security, concerns
  - criminaliteit
- Op elk niveau is data awareness/literacy

DARK PATTERNS

Outcomes:
- lespakket? hoe instrueer je 

Paradigm: Design Science Research (Hefner) / Action Research
- Niet beschouwend, maar ook opbouwend naar een systeem/methode/framework/evaluatietool
- Design Cyclus. 
  - Evaluatie is nog steeds wetenschappelijk
  - Proberen, evalueren, verbeteren


- Overview of all kinds of legislation 
  - @leslieFutureShockGenerative2024