---
title: Discovering a pattern of privacy literacy in rural Sub Saharan Africa
author: Frederik J. Van Deventer
bibliography: references.bib

---

## Context

With the rise of digitization and the data it produces, the question of ownership of data becomes a contested issue for agents such as Indigenous people, consumers and countries [@hummel2021data]. If the ownership is not clear and personal data cannot always be obtained [@herrmannObtainingPersonalData2016] it should be clear we should not only look to data governance but also to privacy literacy [@koltay2016data].
However, much of privacy literacy literature has used ethnocentric Western-based ideas of governance and regulation that do not take into account the multi-varied ways privacy can be perceived in the Global South [@arora2019general; @aroraDecolonizingPrivacyStudies2019].
Digital privacy today faces a lot of threats. Some Big Tech parties have decided to bring a limited version of the internet to the Global South in the last decade [@MetaConnectivity, @IntroducingProjectLoon2013]. 

## Problem

Understanding what happens with your data is difficult and ambigiuous in any context [@bartschControlYourFacebook2016], intuitively this would be even more so where internet is free and provided by commercial companies who have an interest in obtaining your personal data. Companies like Meta profit from tracking users online [@wernerfeltEstimatingValueOffsite2025]. Where the quality or the inner workings of zero-rated services are being assessed [@senFreeBridgeDigital2016, @senWalledGardenDeconstructing2017] results are mixed. On the other hand zero-rated services have significantly contributed to access to information and appointments for Maternal Health or free messaging for HIV/AIDS medical appointments [@layton2016free]. Other critiques of "zero-rating" are issues of net-neutrality and gatekeeping [@galpayaZeroratingEmergingEconomies2017].

## Research questions

### Main question

How can people in Sub Saharan Africa benefit from being "connected" without sacrificing their privacy?

__(Possibly this can be more specified towards a Case Study in rural South Africa, or Botswana?)__

### Sub-questions

- What initiatives stand out in amlerioating the digital divide?
- In what way are people aware of the predicament of sharing personal information?
- What is the benefit of participating in the digital "online world"?
- What legislation is in place to ensure digital privacy at a national and regional level?
- What conflicts between legislation and ethics arise concerning privacy?
- What are main differences when dealing with privacy in Europe and SSA?

## Conceptual Framework

To make sense of this topic I will first set out to place privacy and privacy literacy in conceptual framework.

The model _6 Private I's_ is proposed by @hartman2023privacy as a way to perceive teach privacy and to recognize that privacy firstly concerns people and not just technology.

 According to @rotman2009you for users to consciously decide what happens with their information they should go from _understanding, recognizing, realizing, evaluating_ to _deciding_. But this sounds very generic about anything you can teach..

...

## Research methodology

At the moment I'm reading @hanckeIntelligentResearchDesign2023 and sorting through the vast bibliography of  @sovacoolPromotingNoveltyRigor2018 to help sort out the methodology part.

My initial instinct is to do a survey, but I would like to do something a bit different. But not sure how to go about this.

Some other ideas:

Ideas on how to accomplish this:

- A/B Testing -- do survey's on 2 groups
  - one group has received a seminar or dissemination of the information about privacy the other has not
- Do a deeper but not necessarily wider analysis. So perhaps look for a few groups of participants in rural Botswana and a few groups in urban Botswana. Or try to localize it further by looking at interactions wihtin townships.
- Data acquisition might be a problem.. 


## Significance

A study by @prinslooDataPrivacyAfrican2022 has been held to asses specific sub-topics such as student data privacy researching regulatory frameworks on the African content. The angle here to assess Higher Education Institutes (HEI's) is helpful as it is a very concrete example and produces very clear results. However HEI's are also quite an exclusive segment of society that cannot be used to draw broader conclusions.
Another study uses a survey in an impressive array of countries but has quite a low sample size, primarily in the generation we call millenials, which might be the most digital and privacy literate [@agbozo2018personal].

This study should be different from both previous efforts by both its scope and localization.

## Bibliography