---
title: "Putting human agency at the forefront in agentic AI for adolescents"
authors:
  - name: Frederik J van Deventer
    affiliation: HAN University of Applied Sciences
    roles: writing
    corresponding: true
bibliography: references.bib
# csl: slncs-alphabetical.csl
keywords: human agency, agentic AI, CAIL, turing trap, AI Literacy, belief
---

## Introduction

Over the last decade Artificial Intelligence (AI) has been attributed a _sense of agency_  (SoA)[@legaspiSyntheticAgencySense2019]. Even more so with the emerging paradigm Agentic AI, which is different to previous forms of AI such as large language models (LLMs), because it can operate (semi-)autonomously and pursue complex goals with little human intervention [@acharyaAgentic2025]. This questions the nature of our human future and of our human agency [@andersonFutureHumanAgency2023], as systems now also seem to (1) act with (2) intention and a certain kind of (3) reasoning, three aspects often associated with agency [@anscombe1956intention; @davidsonIntending1978]. In @giddens1984constitution' definition human agency is the capability to "make a difference", in other words to have and be able to exercise power over a situation.

Young people around the globe are growing up in a different digital reality than their parents, where AI is playing a big part. After the "digital natives" of the early 2000's and the debates for evidence that entailed [@bennettDigitalNativesDebate2008], one could argue that we are moving towards a generation of "AI natives" [@poncerojoDigitalNativesAI2025]. A new group of adolescents that spend almost 7 hours and 30 minutes online per day [@kemp2025Digital2025Global2025], on platforms where AI is embedded, e.g. in search algorithms, AI answers, or chat functions often signified with "AI" or ✨.

If Human-like AI (HLAI) or autonomous Artificial General Intelligence is really in the near future, like some believe [@vossWhyWeDont2023; @qureshiThinkingTokensBrainInspired2025], this could have a profound impact on the way our economy is structured and what kind of work is performed by humans and what is performed solely by machines. The already great concentration in economic and political power by technologists is expected to only increase if we focus on replacing human labour by automating tasks instead of augmenting human labour with AI, leading to a situation where those "without power have no way to improve their outcomes", what @brynjolfssonTuringTrapPromise2022 calls the _Turing Trap_.

A situation where power concentrates among the lucky few that are already econonomically and politically powerful and have influence on how HLAI can be deployed is very unlikely to yield larger autonomy, freedom and agency for the majority with marginal ecomonic and political power.

How then do we avoid the Turing Trap for our young people, who form half of the world's population [@WorldPopulationProspects], and increase their capability to "make a difference"?

## Gap

In the course of history, human development has been argued to increase where agency and liberty increase [@PradosdelaEscosura_2022; @senDevelopmentFreedom1999]. Agentic AI and AI goals in general, largely seem to focus on increasing abilities for models or replacing tedious tasks performed by humans. While research has been done about future projections of human agency in conjunction with AI in decision making [@pewFutureHuman2023] and in education [@moutaWhereAgencyMoving2025] it does not deal with how to increase human agency for humans now.



One area of study related to increasing human agency surrounding AI is _AI Literacies_. Learning about AI systems explains how they perform, this demystifies and increases people's insight in these systems [@pinskiAILiteracyUsers2024] which helps to reduce anthropomorphism [@drugaHowChildrensPerceptions2021]. Anthropomorphism is one of the things that can lead to false perceptions and misunderstanding of AI abilities[@barrowAnthropomorphismAIHype2024]. 

## Hook 

_"Technological development has invested the powers that be with
not only more efficient, better and more deadly instruments of coercion but with the instruments of persuasion decidedly more efficient than those hitherto used by the political bosses.."_ - [@mathurTechnologyFreedom]

If we want to create circumstances for technology where humans can thrive we need to be able to accept a pluralistic view of technology. As technology is never just neutral nor is it inherently good or bad [@morrowWhenTechnologiesMakes2014; @heyndelsTechnologyNeutrality2023]. Regulation and policy fueled by ideology (both benefiting the few or the many) has been the driver for the direction this advancement would take us [@johnsonPowerProgressOur2023 pp. 57].

## Research Questions

How can adolescents achieve increased human agency and freedom in a world with agentic AI?

### Sub-questions

1. How are students interacting with agentic AI or GenAI? 
2. How is AI affecting the execution of day-to-day tasks (e.g. study, work, household chores)?
3. How do adolescents rate their sense of agency?
4. What beliefs do adolescents have about AI and its capabilities in relation to their own capabilities?
5. In what ways are AI Literacies affecting these beliefs? 
6. How do adolescents discern hype from reality?
7. In what ways can understanding of these phenomena enhance their freedom of choice?

## Theoretical Framework

@habermas1971technology describes the rationaliy of technology as ideological. The ideology that technological progress is inevitable and oppressive is in direct opposition to the hegemony of Silicon Valley that believes in Innovation at all costs, which @winnerCultInnovationIts2018 calls "Cult of Innovation". Resulting in an almost religious approach to AI and AGI among others [@epsteinSiliconValleysObsession2024]. 

Hegelian _Rationality_ should leads towards freedom and cannot be seen separate from the societal boundaries [@Pippin_2008 p. 122;], where there might be roles one fits instead of actually performing an action by one's own beliefss. 
The concepts of agency put forward by @giddens1984constitution and @bandura2001social emphasise different dimensions. Where Giddens focuses on the social structure, "making a difference", Bandura focuses on aspects that make up individual agency, _intentionality, forethought, self-reactiveness and self-reflectiveness_.

Sense of Agency in relation to Agentic AI or AI in general, is under pressure from societal beliefs and expectations that we have that technology will fullfill. 

```{mermaid}


graph TD
classDef Amber fill:#FFDEAD;
    soa[Sense of Agency among Youth]
    soc[Societal Beliefs] --> AGENCY
    ideology[Technocratic Ideologies] -. drive .-> tec
    tec[Technological Innovations]
    pers[Personal Beliefs about AI] -. shape .->AGENCY
    tec -. influence .-> AGENCY

    subgraph AGENCY["Sense of Agency"]
    direction TB
    Gid[Giddens: Social Structure] --> soa
    Ban[Bandura: Individual] --> soa
    end

class AGENCY Amber;

    %% Sci[Scientific Community] -- Discovers --> Inno((Innovations))
    %% Com[Tech Companies] -. Develop .-> Inno
    %% Inno --> Com
    %% Com -. Fund .-> Sci
    %% Inno -. Lead to .-> Products
    %% Com -- Develop --> Products(New Products)
    %% Products -- Marketed to --> Cu{Customers}
    %% Com -- influence --> Media
    %% Media -. inflates importance .-> Cu
```

<!-- ## Methodology

### Thematic analysis

_Thematic analysis_ will be used as @naeemStepbyStepProcessThematic2023 and @braun2021thematic describe it to find common themes and topics in personal interview with students. Thematic analysis is a more subjective approach to data, where language is central. It requires a _coding_ process that uses semantic and latent codes to categorize statements and find _themes_ and _subthemes_ of meaning in texts.

###  Critical Discourse Analysis

Through _critical discourse analyis_ (CDA) I will look at what kind of language is constructing narratives, describes relations of power and how it creates or reinforces myths [@blommaertCriticalDiscourseAnalysis2000].

CDA tries to find patterns in power dynamics and social effects in discourse. In this analysis we can take the texts further and analyze context and intertextuality to challenge social inequalities. I will focus mainly on step two: _Identify obstacles to addressing the social wrong_ of this process which consists of three stages [@fairclough2013critical]:

1. Analyse dialectical relations
2. Select texts
3. Analyse texts interdiscursively and linguistically  -->


## References