---
title: "Putting human agency at the forefront with Agentic AI"
authors:
  - name: Frederik J van Deventer
    affiliation: HAN University of Applied Sciences
    roles: writing
    corresponding: true
bibliography: references.bib
# csl: slncs-alphabetical.csl
abstract: Agentic AI is a new form of AI which can seemingly act and think semi-autonomously, being able to perform tasks linked to executive functions such as planning, problem-solving and reasoning. These are also areas where we expect students to grow during their studies. This research seeks to uncover how values and beliefs of both students and their environment are changing and the way students encounter Agentic AI, by using the Ultimate Meanings Technique, and mixed-method techniques. To explore what this means for the future the Manoa Scenario technique will be used in focus groups.
keywords: human agency, agentic AI, CAIL, AI Literacy, belief
---

## Introduction

_"[I]n other cases, it’s students who are leaning a little too hard on LLMs to do their work for them, and then at exam time just really aren’t ready."_ says professor Dan Garcia about students failing his classes [@dengExaminingAddressingBarriers2026]. Students today are learning to work with Artificial Intelligence (AI) systems with Large Language Models (LLMs) more and more [@kumarGuidingStudentsUsing2024] and a large number of higher education institutes are even encouraging students to do so [@mcdonaldGenerativeArtificialIntelligence2024] as AI is playing a bigger part in student's academic work, school projects and school policy. The discussion among Software Engineering students and teachers has even moved from "whether" to "how" we should be utilizing these techniques. Is this affecting their freedom to act?

The freedom to act according to one's own intention and volition is often described as **agency** [@skinnerGuideConstructsControl]. It is this freedom that is described as _achieved agency_ when it is **realised** "through the active engagement of individuals with aspects of their contexts-for-action" [@biestaAgencyLearningLifecourse2007], that always exists in an temporal-relational _ecology_ [@biestaHowAgencyPossible], consisting of collective beliefs and structures and _truth_ expressed in instruments such as policies or punitive action [@Foucault1980TruthPower p.131], or as expressed by teachers in their narratives or dispositions [@nesporRoleBeliefsPractice1987].
This _achieved agency_ is under pressure when systems circulate responsibility among human and non-human actors [@leonardiHomoAgenticusAge2025], while it is agency increase in societies that is associated with an improvement in human development [@sen1990development].

The distinction between human and technological agency blurs with Agentic AI (AAI), as AAI can operate (semi-)autonomously and pursue complex goals with little human intervention [@acharyaAgentic2025]. AAI uses instances of Generative AI (GenAI) interfacing with eachother creating seemingly autonomous and agentic systems, as a next step from the GenAI chat-platforms widely in use among students already [@silvennoinenStudentsUsageGenAI2025]. A more concrete example is OpenClaw, which attempts to be a somewhat more AAI consumer-friendly tool, it "sends emails, manages your calendar, checks you in for flights. All from [...] any chat app you already use" [@OpenClawPersonalAI]. This is a remarkable departure from how GenAI is being used. AAI at the moment has already taken hold of the Software Engineering on a large scale, where agents are running in the background to not only write code, but also to write up specifications, documentation, plan tasks, review and evaluate the work, largely leaving humans to manage "software teams" that consist of AI agents.

Executive functions like cognitive flexibility, working memory, or inihibition are shown to strongly relate to study success [@serpellDevelopmentExecutiveFunctions]. These tasks include goal-oriented behaviours and planning, but also reasoning and problem-solving [@diamondExecutiveFunctions2013]. AAI seems to step into exactly these areas where students need to grow during there time at a higher education institute. Technology is never just neutral nor is it inherently good or bad [@morrowWhenTechnologiesMakes2014; @heyndelsTechnologyNeutrality2023] it is there to be assistive to our human needs [@arora2024pessimism p. 32], and changes us just as much as we change it [@bruno1994technical, p.33]. In what direction are we then changing with it, are we changing towards a society where agency increases? If the ecology for agency for students includes systems that are able to handle so many of their executive functioning what opportunities do they have to develop these?


## Research Questions

How can students still develop in order to be able to act towards their volitions in a world where the ecology for goal-oriented behaviour is changing because of Agentic AI?

#### Sub Questions

1. How do values and beliefs shape attitudes and adoption of Agentic AI among students?
2. In what way is Agentic AI entering academic and non-academic tasks and changing the lives of students?
3. How can students focus on the development of executive functions with Agentic AI?

## Methodology

|  | Question | Method| minimum number of participants
|-|-------------------|----|--|
| RQ1 | How do values and beliefs shape adoption of Agentic AI among students? | Thematic Analysis / UMT | n = 6 / n ~ 200
| RQ2 | In what way is Agentic AI entering academic and non-academic tasks and changing the lives of students? | Mixed-Method | n = 5-8 for interviews n ~ 40 for self-report cards
| RQ3 | How can students focus on the development of executive functions with Agentic AI? | Scenario Development and focus groups |  n = 20-40

: Research Questions and how they relate to methods {.striped} 

### RQ1: Thematic Analysis and UMT

As clarified in the Knowledge Gap, there is a close relation between action and belief, however in the context of Agentic AI the values and beliefs among students. In @kramerTeachersBeliefsComponent2019 the word _worldview_ is used to describe this belief, which in @biestaHowAgencyPossible's definition would contribute to the _ecology_. The way this is investigated in @kramerTeachersBeliefsComponent2019 is through the use of @leontievApproachingWorldviewStructure2007's Ultimate Meanings Technique (UMT). 

Where @kramerTeachersBeliefsComponent2019 used UMT to discover worldview among teachers I will investigate among a small group of students. The Ultimate Meanings Technique is a form of structured interview, that allows for easily being recorded on paper while conducting it. By starting out with a general "why"-question, the interviewer notes the answer(s) and continues of questioning line until an 'ultimate explainable meaning' is reached. The answers to the questions can be structured hierarchically in a nodal structure, like a "mind map", which in UMT terms is called the _meaning tree_.

To analyse this the interviews will be analysed:

1. Structurally by looking at the structure of a meaning tree. In the structural analysis repetition, negative statements and categories are identified.
2. With content analysis that focuses on the way a subject is using both negative and positive language to display connectedness with people in the direct environment and society at large, concerning one with oneself at the cost of goal-directed activity, and self-restriction and what one does not allow oneself to do. To give an example to the question: "Why do people go to school?" -> "To _not_ fall behind", "To be able to find a job". Etc. 
3. Phenomenologically to describe how the person projects worldview on things in the word to be, rather than how they are. By doing this finding more subjective meanings.

The results of a UMT can then be used to discuss with students to further investigate if what they believe to give meaning and is important to them also corresponds to how they interact and adopt Agentic AI. _Thematic analysis_ can be used as @naeemStepbyStepProcessThematic2023 and @braun2021thematic describe it to find common themes and topics in personal qualitative interview with students to concerning these worldviews and beliefs.

After the initial analysis, when larger themes are recognized questions will be formulated to be able to use a more quantitative approach in the form of a survey.

### RQ2: Mixed-method

To find out where and how this impacts students lives I want to follow the academic and non-academic tasks of a small number of students to find out where AAI / GenAI is confronting students with its actions. Similar to what @ferrariUnderstandingAcademicNonacademic2000 did concerning tasks and procrastination only focusing not on task completion but on whether tasks are affected by AAI / GenAI and how students feel about this.

Students in project education will be asked to write down three tasks that they intend to complete for five consecutive days and will be asked to score along different dimensions how AAI / GenAI is affecting their completion of the task and how students deal with restrictions laid upon by school policy or assignment rules.

The analysis would then consist of comparing tasks among these dimensions, to categorize the type of tasks, their importance to the subject and to compare tasks and scoring between subjects in which way they subvert or conform to the rules.

Before doing this I would like to interview a small group of students to determine which kind of tasks and dimensions would make the most sense and what kind of AAI or GenAI tools are relevant to ask about. For the questions and categories questions from Sense of Agency-scale (SoAS) developed by @tapalsenseofagencyscale2017 will be adapted.

### RQ3: Scenario development

We can not predict the future, nor can we extrapolate from current events with certainty. The Manoa Technique by @schultzManoaFutureNot2015 is a scenario development technique that exists to help us explore possible futures. For this study it seems suited as you it allows you to inquire after a number of dimensions and create a cross-impact matrix where the changes that intersect can be identified.

For this to work I will work through almost all of the steps as @schultzManoaFutureNot2015 puts them forward:

1. Sketch out a future wheel that poses the emerging issue of Agentic AI in different ways: 
   1. as one that infringes upon student goal-orientation
   2. as one that is compatible with student goal-orientation
   3. as one where student goal-orientation are largely dependent on the use of AAI
2. With a group I will create a setting where we can map influences and interconnections
3. Probe more deeply to cover different aspects of student reality (e.g. how student life connects with family life, behaviour as consumer, social relations, as a citizen etc.)
4. Characterize the scenario
5. Build an emerging narrative
6. Stretch the narrative

The main goal is to creatively diverge and find a lot of different outcomes.

In another focus group I will evaluate what the most probable outcomes will be and what solutions might be offered to help inform school policy.

### Sampling and data collection

As mentioned above the initial interviews will be conducted among a group of students. To come with a representative view of students I will seek out students in different areas of expertise. Within our institute of the HAN there are students that follow programs for law, economics, teaching, medical professions, building engineering, informatics amongst others. And in different years. For the first interviews it will be difficult to distritube this evenly.

For the surveys I will go through student organizations for the different fields of expertise, which have closer relationships with students, to be able to distribute widely as well as to acquire a large number of respondents. Within the insitute there are about 30.000 students that are working on a bachelor-diploma, so it would seem feasible to come with enough respondents even if only 1% of active students respond.

For the mixed-method analysis a reward system would make sense as students would be spending quite some time on their task cards similar to the research performed by @ferrariUnderstandingAcademicNonacademic2000.


## Knowledge Gap / Scientific Contribution

Literature focusing on AAI is scarce, unlike the literature for GenAI, which is closely related as precursor to AAI. This shows the need to further examine the phenomenon of AAI in relation to students. Where GenAI is used in studies results can be used as corollary for the type of results for AAI.

The way AAI or GenAI is influencing agency in students seems not to have been studied, apart from the influence it has on critical thinking [@surianoStudentInteractionChatGPT2025], and why and how they use it for studying [@silvennoinenStudentsUsageGenAI2025].

While research has been done about future projections of human agency in conjunction with AI in decision making [@pewFutureHuman2023] and in education [@moutaWhereAgencyMoving2025] it does not deal with how achieved agency for humans now. Or how AAI is changing realized intentions.

Theorizations of agency by @biestaAgencyLearningLifecourse2007 clarify that action flows from the values and beliefs of a person. This study will try to deepen understanding on this interplay of beliefs and agency realised in the context of Agentic AI among students. As action and belief are tied together closely [@mccormickBelievingEvidence2014] it is relevant to investigate these beliefs that inform action further.

It does not seem like a logical stretch to be able to come up with multiple applications where this would either enhance or infringe human agency. For example it might help to come up with ideas or to automate task distribution, but it might also take away freedom to interfere with an automated planning, to look beyond the ideas that the platform comes up with, or only delve into information sources widely available instead more local or native knowledge.

The way students already interact with these systems and their outcomes would suggest it worthwhile to investigate to assess the impact is having.

This both pushes the body of scientific knowledge, but also helps to adjust or assert our opinions as a public towards these systems and the role they are already having in our workplace and society at large. As the research will be performed at the HAN UAS the findings will also be discussed in panels that deal with AI and Ethics to advise the board of directors for future decisions.

The Inclusive AI Lab in Utrecht which is part of the Utrecht University seeks to incorporate research findings in real world AI applications that are sustainable and inclusive. This opens the societal impact to a much wider audience.

Within the group of Interaction Technology of which promotor Prof dr. ir. Masthoff is a part of there is a great need for exploring future implications of Agentic AI.

Second supervisor Dr. Herder is part of the ACM Technology Policy Council, so the findings of this research could dictate on a larger scale how policy can be shaped.

The impact for science will be increased by publishing the findings as separate papers and not a complete booklet at the end of the PhD-program. So findings can be used quickly.


## References