---
author: Fritz Van Deventer
bibliography: ../references.bib
date: 2026-04-08
title: agency teacher
---

Young people different world.
Agentic AI
The way we perceive Agency itself is changing, we attribute it to systems
Agency is in its essence a way to look at being able to achieve volitions
Students need to navigate this new notion of agency
How is agentic ai changing the way students interact with their surroundings.. ?



“Nostalgia has no survival value in the modern world and can only be considered a flight into dreamland. ” p. 400 Technological Society Jacques Ellul

Essence is existence and existence is action. If l define you by what you have (the gun), and by
the series of associations that you enter into when you use what you have (when you fire the
gun), then you are modified by the gun – more so or less so, depending on the weight of the
other associations that you carry. This translation is wholly symmetrical. You are different
with a gun in hand; the gun is different with you holding it. You are another subject because
you hold the gun; the gun is another object because it has entered into a relationship with
you. (Latour 1994a, 33)

Excerpt From
The Oxford Handbook of Philosophy of Technology
Shannon Vallor;
This material may be protected by copyright. 