---
title: "Putting human agency at the forefront in agentic AI for adolescents"
authors:
  - name: Frederik J van Deventer
    affiliation: HAN University of Applied Sciences
    roles: writing
    corresponding: true
bibliography: references.bib
# csl: slncs-alphabetical.csl
keywords: human agency, agentic AI, CAIL, turing trap, AI Literacy, belief
---

## Introduction

Young people around the globe are growing up in a different digital reality than their parents, where Artificial Intelligence (AI) is playing a big part. After the "digital natives" of the early 2000's and the debates for evidence that entailed [@bennettDigitalNativesDebate2008], one could argue that we are moving towards a generation of "AI natives" [@poncerojoDigitalNativesAI2025]. A new group of adolescents that spend almost 7 hours and 30 minutes online per day [@kemp2025Digital2025Global2025], on platforms where AI is embedded, e.g. in search algorithms, AI answers, or chat functions often signified with "AI" or ✨.

Over the last decade the question whether Artificial Intelligence (AI) itself exhibits agency has been debated [@legaspiSyntheticAgencySense2019; @swanepoelDoesArtificialIntelligence2021]. This distinction between human and technological agency becomes more blurred with the emerging paradigm of Agentic AI, which is different to previous forms of AI such as large language models (LLMs), because it can operate (semi-)autonomously and pursue complex goals with little human intervention [@acharyaAgentic2025].

This questions the nature of our human future and of our human agency [@andersonFutureHumanAgency2023], as systems now also seem to (1) act with (2) intention and a certain kind of (3) reasoning, three aspects often associated with agency [@anscombe1956intention; @davidsonIntending1978]. In @giddens1984constitution' structuralist definition of human agency, placed within society, it is the capability to "make a difference", in other words to have and be able to exercise power over a situation in a certain context or structure [@giddens1984constitution].

If Human-like AI (HLAI) or autonomous Artificial General Intelligence is really in the near future, like some believe [@vossWhyWeDont2023; @qureshiThinkingTokensBrainInspired2025], this could have a profound impact on the way our economy is structured and what kind of work is performed by humans and what is performed solely by machines. The already great concentration in economic and political power by technologists is expected to only increase if we focus on replacing human labour by automating tasks instead of augmenting human labour with AI, leading to a situation where those "without power have no way to improve their outcomes", what @brynjolfssonTuringTrapPromise2022 calls the _Turing Trap_.

A situation where power concentrates among the lucky few that are already econonomically and politically powerful and have influence on how HLAI can be deployed is very unlikely to yield larger autonomy, freedom and agency for the majority with marginal ecomonic and political power.

How then do we avoid the Turing Trap for our young people, who form half of the world's population [@WorldPopulationProspects], and increase their capability to "make a difference"?

## Gap

In the course of history, human development has been argued to increase where agency and freedom increase [@PradosdelaEscosura_2022; @senDevelopmentFreedom1999]. Agency is however a bloated term that can mean a number of things in different domains, such as psychology where it focuses on individual human agency [@bandura2001social], sociology where it focuses on the structures within an actor operates [@giddens1984constitution]. Agency is a term closely related to and with overlaps to terms such as autonomy and freedom. To be clear in this context "agency" means for an actor to be free to act true to that same actor's intentions.

This in itself is impossible to measure, being dependent on so many factors. But some attempts have been made to measure how people perceive their _sense of agency_ [@tapalsenseofagencyscale2017] or how Trust in Automation (TiA) influences there autonomy [@kohnMeasurementTrustAutomation2021]. Also different models that propose "measures of agency" [@grunbaumMeasuresAgency2020] or how concepts like autonomy and ability contribute to agency or measuring proxies for agency [@alkire2008concepts].

Agentic AI and AI goals in general, largely seem to focus on increasing abilities for models or replacing tedious tasks performed by humans. While research has been done about future projections of human agency in conjunction with AI in decision making [@pewFutureHuman2023] and in education [@moutaWhereAgencyMoving2025] it does not deal with how to increase human agency for humans now. Or what the effect is of Agentic AI on Sense of Agency (SoA).

The way Agentic AI or AI in general is influencing agency in adolescents seems not to have been studied, apart from the influence it has on critical thinking [@surianoStudentInteractionChatGPT2025], and why and how they use it for studying [@daiWhyStudentsUse2025; @silvennoinenStudentsUsageGenAI2025; @suonpaaStudentsPerceptionsGenerative2024].

While the Human AI - Interaction framework suggested by @sundarRiseMachineAgency2020 incorporates agency, it does not investigate the different angles it proposes as interesting.

One area of study related to increasing human agency surrounding AI is _AI Literacies_. Learning about AI systems explains how they perform, this demystifies and increases people's insight in these systems [@pinskiAILiteracyUsers2024] which helps to reduce anthropomorphism [@drugaHowChildrensPerceptions2021]. Anthropomorphism is one of the things that can lead to false perceptions and misunderstanding of AI abilities[@barrowAnthropomorphismAIHype2024]. AI Literacies among adolescents has not been studied in relation to their human agency.

In goal attainment and AI assisted coaching, there is a real opportunity for an AI to participate in the process  this then is suggested to increase agency [@plotkinaUnearthingAICoaching2024]. A literature review collecting these kinds of studies, that are influential to agency is however hard to find.

## Hook 

If we want to create circumstances for technology where humans can thrive we need to be able to accept a pluralistic view of technology. As technology is never just neutral nor is it inherently good or bad [@morrowWhenTechnologiesMakes2014; @heyndelsTechnologyNeutrality2023]. Regulation and policy fueled by ideology (both benefiting the few or the many) has been the driver for the direction this advancement would take us [@johnsonPowerProgressOur2023 pp. 57]. 

_(Feenberg 10 paradoxes of technology, equal and opposed reaction, of Adorno Instrumental Rationality)_

It is therefore imperative to understand how and why agency is being threatened and how agency can be increased in the context of Agentic AI. That firstly means understanding how we can assess agency is being influenced. I propose using and translating the Sense of Agency Scale [@tapalsenseofagencyscale2017] to the context of Agentic AI. Secondly what kind of influence AI Literacy can have on understanding Agentic AI.

## Research Questions

How is technological ideology, which manifests itself as Agentic AI, impacting capabilities for adolescent human agency and how can its negative impacts be mitigated?

### Sub-questions

1. What influence is Agentic AI or AI in general having on proxies of agency or related concepts?
2. How are adolescents interacting with agentic AI and how is this affecting the execution of day-to-day tasks (e.g. study, work, household chores)?
3. How do adolescents rate their sense of agency on the Scale of Sense of Agency [@tapalsenseofagencyscale2017]?
4. In what ways can understanding of these phenomena enhance their capabilities?

## Methodology

In the following section I will elaborate on how I will conduct the research described in the above mentioned research questions.

|  | Question | Method|
|---------|-----------|--------|
| RQ1 | What influence is Agentic AI or AI in general having on proxies of agency or related concepts? | Systematic Literature Review |
| RQ2 | How are adolescents interacting with agentic AI and how is this affecting the execution of day-to-day tasks (e.g. study, work, household chores)?  | Mixed-method
| RQ3 | How do adolescents rate their sense of agency on the Scale of Sense of Agency [@tapalsenseofagencyscale2017]? | Survey
| RQ4 | In what ways can understanding of these phenomena enhance their capabilities? | Intervention

### RQ1: Systematic Literature Review

To find out what studies related to agency a systematic literature will be conducted that searches for studies that relate to agency, such as studies that focus on empowerment [@kongDevelopingValidatingScale2025]. According to the systems of @grunbaumMeasuresAgency2020 and @alkire2008concepts when studies are performed on proxies of agency, or related concepts, they can be categorized and labeled in relation to AI or more specifically to Agentic AI if those are available.

### RQ2: Mixed-method

_Thematic analysis_ will be used as @naeemStepbyStepProcessThematic2023 and @braun2021thematic describe it to find common themes and topics in personal qualitative interview with adolescents. Thematic analysis is a more subjective approach to data, where language is central. It requires a _coding_ process that uses semantic and latent codes to categorize statements and find _themes_ and _subthemes_ of meaning in texts.

After the initial analysis I will make a survey that can study the outcomes of the main themes with a larger group of adolescents quantitatively.

### RQ3: ?

### RQ4: 

This is where an intervention like AI Literacies will take center stage to see if this can help understand Agentic AI better to find out if a better way to deal and cope with these technologies helps adolescents to use these more properly.


## Theoretical Framework

@habermas1971technology describes the rationality of technology as ideological. His ideology that technological progress is inevitable and oppressive [@habermas1971technology] is in direct opposition to the techno-optimistic hegemony of Silicon Valley that believes in Innovation at all costs with determinist and positivist view of its results, which @winnerCultInnovationIts2018 calls "Cult of Innovation". Resulting in an almost religious approach to AI and AGI among others [@epsteinSiliconValleysObsession2024].

The acceptance of society of this belief in progress by technological means influences and steers decision-making. @feenberg2009technology social factors and technical override technological deternimism. We do not have to blindly follow technology where it leads. There is no inevitability for the course technology takes society.

```{mermaid}

graph TD
classDef Amber fill:#FFDEEF;
    soa(Sense of Agency among Youth)
    soc(Societal Beliefs) --> AGENCY
    ideology(Technocratic Ideologies) -. drive .-> tec
    tec(Technological Innovations)
    pers(Personal Beliefs about AI) -. shape .->AGENCY
    tec -. influence .-> AGENCY

    subgraph AGENCY["Sense of Agency"]
    direction TB
    Gid(Giddens: Social Structure) --> soa
    Ban(Bandura: Individual) --> soa
    end

class AGENCY Amber;
```

<!-- ## Planning

```{mermaid}
gantt
    title Planning PhD
    dateFormat YYYY
    section Literary Framework
        A task          :a1, 2027-01-01, 240d
        Another task    :a2, 2027-08-01, 365d
    section Another
        Task in Another :b1, 2028-01-01, 365d
        another task    :after b1, 365d
``` -->

<!-- ## Methodology

### Thematic analysis

_Thematic analysis_ will be used as @naeemStepbyStepProcessThematic2023 and @braun2021thematic describe it to find common themes and topics in personal interview with students. Thematic analysis is a more subjective approach to data, where language is central. It requires a _coding_ process that uses semantic and latent codes to categorize statements and find _themes_ and _subthemes_ of meaning in texts.

###  Critical Discourse Analysis

Through _critical discourse analyis_ (CDA) I will look at what kind of language is constructing narratives, describes relations of power and how it creates or reinforces myths [@blommaertCriticalDiscourseAnalysis2000].

CDA tries to find patterns in power dynamics and social effects in discourse. In this analysis we can take the texts further and analyze context and intertextuality to challenge social inequalities. I will focus mainly on step two: _Identify obstacles to addressing the social wrong_ of this process which consists of three stages [@fairclough2013critical]:

1. Analyse dialectical relations
2. Select texts
3. Analyse texts interdiscursively and linguistically  -->


## References