---
title: Understanding privacy AI in the context of digital literacy
author: Fritz Van Deventer
bibliography: references.bib

---

## Introduction

Digital connectivity is a must for advancing economic growth and personal development, whether we like it or not. Digital privacy however is something we often neglect, or is a luxury to consider [@papacharissiPrivacyLuxuryCommodity2010], when most communication platforms require a privacy sacrifice to partake in its benefits for free.
Low digital literacy in combination with high connectivity can be dangerous. Multiple studies have seen a combination of reasons why some people are more prone to be a victim of fraud, one of which is low digital literacy [@liDoesDigitalLiteracy2024]. Most people are not aware that all the small bits and pieces we offer to social platforms can be used by big tech companies to put together a "Gestalt" of a user [@puaschunder2018dignity]. Or put more simply, to understand what constitutes and drives an individual online.

In the quest to increase profits and acquire the "next billion users", big tech companies are trying to get more people online and part of their platforms by offering zero-rated services [@MetaConnectivity], [more sources]. The benefits of LLM's and GenAI are largely available for free where users offer a lot of details about private matters, work-related documents without clearly stating what is being done with their data.

Besides that GenAI makes it a lot easier to cause harm by creating misinformation at the speed of light, and enhance digital images and videos that some people cannot descern from real.

How then do people in low digital literacy environments educate themselves to guard themselves against these forces?